code: 0102800000
location_name: 'Currimao, Ilocos Norte'
district: 2
marks:
  # BARANGAY POSITIONS
  # PUNONG_BARANGAY-1402702011 (Row A)
  - key: A1
    value: 'LD_001'
  - key: A2
    value: 'SJ_002'
  - key: A3
    value: 'DW_003'
  - key: A4
    value: 'MS_004'
  - key: A5
    value: 'BP_005'
  - key: A6
    value: 'AJ_006'

  # MEMBER_SANGGUNIANG_BARANGAY-1402702011 (Rows B-J, 6 bubbles per row)
  # Row B (candidates 1-6)
  - key: B1
    value: 'JD_001'
  - key: B2
    value: 'ES_002'
  - key: B3
    value: 'MF_003'
  - key: B4
    value: 'JL_004'
  - key: B5
    value: 'CB_005'
  - key: B6
    value: 'SB_006'
  # Row C (candidates 7-12)
  - key: C1
    value: 'WS_007'
  - key: C2
    value: 'JR_008'
  - key: C3
    value: 'MD_009'
  - key: C4
    value: 'CT_010'
  - key: C5
    value: 'KR_011'
  - key: C6
    value: 'NK_012'
  # Row D (candidates 13-18)
  - key: D1
    value: 'HJ_013'
  - key: D2
    value: 'ZS_014'
  - key: D3
    value: 'BC_015'
  - key: D4
    value: 'GG_016'
  - key: D5
    value: 'JG_017'
  - key: D6
    value: 'AA_018'
  # Row E (candidates 19-24)
  - key: E1
    value: 'DC_019'
  - key: E2
    value: 'KW_020'
  - key: E3
    value: 'MR_021'
  - key: E4
    value: 'EB_022'
  - key: E5
    value: 'CE_023'
  - key: E6
    value: 'RM_024'
  # Row F (candidates 25-30)
  - key: F1
    value: 'CB_025'
  - key: F2
    value: 'TS_026'
  - key: F3
    value: 'JM_027'
  - key: F4
    value: 'OS_028'
  - key: F5
    value: 'RG_029'
  - key: F6
    value: 'SH_030'
  # Row G (candidates 31-36)
  - key: G1
    value: 'JR_031'
  - key: G2
    value: 'Z_032'
  - key: G3
    value: 'JB_033'
  - key: G4
    value: 'MY_034'
  - key: G5
    value: 'MA_035'
  - key: G6
    value: 'EG_036'
  # Row H (candidates 37-42)
  - key: H1
    value: 'TC_037'
  - key: H2
    value: 'FP_038'
  - key: H3
    value: 'PP_039'
  - key: H4
    value: 'RM_040'
  - key: H5
    value: 'ATJ_041'
  - key: H6
    value: 'IE_042'
  # Row I (candidates 43-48)
  - key: I1
    value: 'PD_043'
  - key: I2
    value: 'A_044'
  - key: I3
    value: 'JC_045'
  - key: I4
    value: 'AG_046'
  - key: I5
    value: 'TH_047'
  - key: I6
    value: 'LN_048'
  # Row J (candidates 49-50)
  - key: J1
    value: 'BC_049'
  - key: J2
    value: 'HM_050'
